---
- name: Update apt cache and upgrade packages
  apt:
    update_cache: yes
    upgrade: 'dist'

- name: Install essential packages
  apt:
    name:
      - git
      - build-essential
      - curl
    state: present
